---
http_interactions:
- request:
    method: get
    uri: https://api.bestbuy.com/v1/products(search=sennheiser)?apiKey=57f9xyfxh9ujc522eek6ugd4&format=json&pageSize=15&show=sku,name,customerReviewAverage,shortDescription,image,salePrice
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - Faraday v0.9.2
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
  response:
    status:
      code: 200
      message: OK
    headers:
      X-Mashery-Responder:
      - prod-j-worker-lax-02.mashery.com
      Content-Type:
      - application/json; charset=UTF-8
      Content-Length:
      - '7033'
      Server:
      - thin 1.6.1 codename Death Proof
      Date:
      - Tue, 08 Mar 2016 19:00:25 GMT
      Connection:
      - close
    body:
      encoding: UTF-8
      string: |-
        {
          "from": 1,
          "to": 15,
          "total": 165,
          "currentPage": 1,
          "totalPages": 11,
          "queryTime": "0.004",
          "totalTime": "0.041",
          "partial": false,
          "canonicalUrl": "/v1/products(search=\"sennheiser\")?show=sku,name,customerReviewAverage,shortDescription,image,salePrice&format=json&apiKey=57f9xyfxh9ujc522eek6ugd4",
          "products": [
            {
              "sku": 4763330,
              "name": "Galaxy Audio - Headset Microphone - Beige",
              "customerReviewAverage": null,
              "shortDescription": "GALAXY AUDIO Headset Microphone: Crafted for most wireless transmitters; can be used with a JIB/PB; works with most PC sound cards; flexible fit design",
              "image": "http://images.bestbuy.com/BestBuy_US/images/products/4763/4763330_sa.jpg",
              "salePrice": 199.99
            },
            {
              "sku": 4763305,
              "name": "Galaxy Audio - Headset Microphone - Black",
              "customerReviewAverage": null,
              "shortDescription": "GALAXY AUDIO Headset Microphone: Compatible with most wireless transmitters; can be used with a JIB/PB; works with most PC sound cards; flexible fit design",
              "image": "http://images.bestbuy.com/BestBuy_US/images/products/4763/4763305_sa.jpg",
              "salePrice": 199.99
            },
            {
              "sku": 4763306,
              "name": "Galaxy Audio - Headset Microphone - Black",
              "customerReviewAverage": null,
              "shortDescription": "GALAXY AUDIO Headset Microphone: Crafted for most wireless transmitters; can be used with a JIB/PB; works with most PC sound cards; flexible fit design",
              "image": "http://images.bestbuy.com/BestBuy_US/images/products/4763/4763306_sa.jpg",
              "salePrice": 199.99
            },
            {
              "sku": 4763315,
              "name": "Galaxy Audio - Headset Microphone - Cocoa",
              "customerReviewAverage": null,
              "shortDescription": "GALAXY AUDIO Headset Microphone: Crafted for most wireless transmitters; can be used with a JIB/PB; works with most PC sound cards; flexible fit design",
              "image": "http://images.bestbuy.com/BestBuy_US/images/products/4763/4763315_sa.jpg",
              "salePrice": 199.99
            },
            {
              "sku": 4763316,
              "name": "Galaxy Audio - Headset Microphone - Cocoa",
              "customerReviewAverage": null,
              "shortDescription": "GALAXY AUDIO Headset Microphone: Compatible with most wireless transmitters; can be used with a JIB/PB; works with most PC sound cards; flexible fit design",
              "image": "http://images.bestbuy.com/BestBuy_US/images/products/4763/4763316_sa.jpg",
              "salePrice": 199.99
            },
            {
              "sku": 4763322,
              "name": "Galaxy Audio - Omnidirectional Headset Microphone - Beige",
              "customerReviewAverage": null,
              "shortDescription": "GALAXY AUDIO Omnidirectional Headset Microphone: Designed for select Sennheiser wireless devices; omnidirectional polar pattern; 20Hz - 20kHz frequency response; -65dB sensitivity; flexible fit design",
              "image": "http://images.bestbuy.com/BestBuy_US/images/products/4763/4763322_sa.jpg",
              "salePrice": 199.99
            },
            {
              "sku": 2602352,
              "name": "Sennheiser - Active Noise-Canceling Headphones - Black",
              "customerReviewAverage": "2.7",
              "shortDescription": "From our expanded online assortment; TalkThrough function; NoiseGard Digital noise cancellation; 10mm drivers",
              "image": "http://images.bestbuy.com/BestBuy_US/images/products/2602/2602352_sa.jpg",
              "salePrice": 229.99
            },
            {
              "sku": 1700513,
              "name": "Sennheiser - Audiophile Over-the-Ear Headphones - Titan",
              "customerReviewAverage": "4.5",
              "shortDescription": "Eargonomic Acoustic Refinement technology; Duofol diaphragm technology; neodymium ferrous magnet; aluminum voice coils",
              "image": "http://images.bestbuy.com/BestBuy_US/images/products/1700/1700513_sa.jpg",
              "salePrice": 179.98
            },
            {
              "sku": 9637018,
              "name": "Sennheiser - Binaural Headphone - Black",
              "customerReviewAverage": "4.5",
              "shortDescription": "Stereo - Black - Wireless - RF - 60 ft - 32 Ohm - 18 Hz 21 kHz - Over-the-head - Binaural - Circumaural",
              "image": "http://images.bestbuy.com/BestBuy_US/images/products/9637/9637018_sa.jpg",
              "salePrice": 199.99
            },
            {
              "sku": 9636974,
              "name": "Sennheiser - Binaural Headphone - Black",
              "customerReviewAverage": "4.4",
              "shortDescription": "Wired Connectivity - Surround - Over-the-head - Black",
              "image": "http://img.bbystatic.com/BestBuy_US/images/products/9636/9636974_rc.jpg",
              "salePrice": 69.99
            },
            {
              "sku": 9678429,
              "name": "Sennheiser - Camera-Mount Wireless Microphone System - Black",
              "customerReviewAverage": null,
              "shortDescription": "SENNHEISER Camera-Mount Wireless Microphone System: Invisible clip-on microphone; sturdy metal housing; automatic frequency management; easy-to-read illuminated display; 4-level battery indicator; 626-668MHz frequency range",
              "image": "http://images.bestbuy.com/BestBuy_US/images/products/9678/9678429_sa.jpg",
              "salePrice": 629.95
            },
            {
              "sku": 9678447,
              "name": "Sennheiser - Camera-Mount Wireless Microphone System - Black",
              "customerReviewAverage": null,
              "shortDescription": "SENNHEISER Camera-Mount Wireless Microphone System: Invisible clip-on microphone; sturdy metal housing; automatic frequency management; easy-to-read illuminated display; 4-level battery indicator; 566-608MHz frequency range",
              "image": "http://images.bestbuy.com/BestBuy_US/images/products/9678/9678447_sa.jpg",
              "salePrice": 629.95
            },
            {
              "sku": 6131454,
              "name": "Sennheiser - CH 650 S 10' Balanced Headphone Cable - Black",
              "customerReviewAverage": null,
              "shortDescription": "SENNHEISER CH 650 S 10' Balanced Headphone Cable: Compatible with Sennheiser headphone amplifiers; oxygen-free copper cables; gold-plated contacts; 4pole XLR with 2 mini plugs",
              "image": "http://images.bestbuy.com/BestBuy_US/images/products/6131/6131454_sa.jpg",
              "salePrice": 239.99
            },
            {
              "sku": 6131463,
              "name": "Sennheiser - CH 700 S 10' Balanced Headphone Cable - Black",
              "customerReviewAverage": null,
              "shortDescription": "SENNHEISER CH 700 S 10' Balanced Headphone Cable: Compatible with Sennheiser headphones and headphone amplifiers; oxygen-free copper cables with silver coating; gold-plated contacts; 4pole XLR with two 2.5mm jacks",
              "image": "http://img.bbystatic.com/BestBuy_US/images/products/6131/6131463_rc.jpg",
              "salePrice": 319.99
            },
            {
              "sku": 6131445,
              "name": "Sennheiser - CH 800 S 10' Balanced Headphone Cable - Black",
              "customerReviewAverage": null,
              "shortDescription": "SENNHEISER CH 800 S 10' Balanced Headphone Cable: Compatible with Sennheiser headphones and headphone amplifiers; oxygen-free copper cables with silver coating; gold-plated contacts; 4pole XLR with 2 ODU connectors",
              "image": "http://img.bbystatic.com/BestBuy_US/images/products/6131/6131445_rc.jpg",
              "salePrice": 379.99
            }
          ]
        }
    http_version: 
  recorded_at: Tue, 08 Mar 2016 19:00:25 GMT
- request:
    method: get
    uri: https://api.bestbuy.com/v1/products(search=sennheiser)?apiKey=57f9xyfxh9ujc522eek6ugd4&format=json&pageSize=15&show=sku,name,customerReviewAverage,shortDescription,image,salePrice
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - Faraday v0.9.2
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
  response:
    status:
      code: 200
      message: OK
    headers:
      X-Mashery-Responder:
      - prod-j-worker-lax-03.mashery.com
      Content-Type:
      - application/json; charset=UTF-8
      Content-Length:
      - '7033'
      Server:
      - thin 1.6.1 codename Death Proof
      Date:
      - Tue, 08 Mar 2016 19:00:25 GMT
      Connection:
      - close
    body:
      encoding: UTF-8
      string: |-
        {
          "from": 1,
          "to": 15,
          "total": 165,
          "currentPage": 1,
          "totalPages": 11,
          "queryTime": "0.004",
          "totalTime": "0.041",
          "partial": false,
          "canonicalUrl": "/v1/products(search=\"sennheiser\")?show=sku,name,customerReviewAverage,shortDescription,image,salePrice&format=json&apiKey=57f9xyfxh9ujc522eek6ugd4",
          "products": [
            {
              "sku": 4763330,
              "name": "Galaxy Audio - Headset Microphone - Beige",
              "customerReviewAverage": null,
              "shortDescription": "GALAXY AUDIO Headset Microphone: Crafted for most wireless transmitters; can be used with a JIB/PB; works with most PC sound cards; flexible fit design",
              "image": "http://images.bestbuy.com/BestBuy_US/images/products/4763/4763330_sa.jpg",
              "salePrice": 199.99
            },
            {
              "sku": 4763305,
              "name": "Galaxy Audio - Headset Microphone - Black",
              "customerReviewAverage": null,
              "shortDescription": "GALAXY AUDIO Headset Microphone: Compatible with most wireless transmitters; can be used with a JIB/PB; works with most PC sound cards; flexible fit design",
              "image": "http://images.bestbuy.com/BestBuy_US/images/products/4763/4763305_sa.jpg",
              "salePrice": 199.99
            },
            {
              "sku": 4763306,
              "name": "Galaxy Audio - Headset Microphone - Black",
              "customerReviewAverage": null,
              "shortDescription": "GALAXY AUDIO Headset Microphone: Crafted for most wireless transmitters; can be used with a JIB/PB; works with most PC sound cards; flexible fit design",
              "image": "http://images.bestbuy.com/BestBuy_US/images/products/4763/4763306_sa.jpg",
              "salePrice": 199.99
            },
            {
              "sku": 4763315,
              "name": "Galaxy Audio - Headset Microphone - Cocoa",
              "customerReviewAverage": null,
              "shortDescription": "GALAXY AUDIO Headset Microphone: Crafted for most wireless transmitters; can be used with a JIB/PB; works with most PC sound cards; flexible fit design",
              "image": "http://images.bestbuy.com/BestBuy_US/images/products/4763/4763315_sa.jpg",
              "salePrice": 199.99
            },
            {
              "sku": 4763316,
              "name": "Galaxy Audio - Headset Microphone - Cocoa",
              "customerReviewAverage": null,
              "shortDescription": "GALAXY AUDIO Headset Microphone: Compatible with most wireless transmitters; can be used with a JIB/PB; works with most PC sound cards; flexible fit design",
              "image": "http://images.bestbuy.com/BestBuy_US/images/products/4763/4763316_sa.jpg",
              "salePrice": 199.99
            },
            {
              "sku": 4763322,
              "name": "Galaxy Audio - Omnidirectional Headset Microphone - Beige",
              "customerReviewAverage": null,
              "shortDescription": "GALAXY AUDIO Omnidirectional Headset Microphone: Designed for select Sennheiser wireless devices; omnidirectional polar pattern; 20Hz - 20kHz frequency response; -65dB sensitivity; flexible fit design",
              "image": "http://images.bestbuy.com/BestBuy_US/images/products/4763/4763322_sa.jpg",
              "salePrice": 199.99
            },
            {
              "sku": 2602352,
              "name": "Sennheiser - Active Noise-Canceling Headphones - Black",
              "customerReviewAverage": "2.7",
              "shortDescription": "From our expanded online assortment; TalkThrough function; NoiseGard Digital noise cancellation; 10mm drivers",
              "image": "http://images.bestbuy.com/BestBuy_US/images/products/2602/2602352_sa.jpg",
              "salePrice": 229.99
            },
            {
              "sku": 1700513,
              "name": "Sennheiser - Audiophile Over-the-Ear Headphones - Titan",
              "customerReviewAverage": "4.5",
              "shortDescription": "Eargonomic Acoustic Refinement technology; Duofol diaphragm technology; neodymium ferrous magnet; aluminum voice coils",
              "image": "http://images.bestbuy.com/BestBuy_US/images/products/1700/1700513_sa.jpg",
              "salePrice": 179.98
            },
            {
              "sku": 9637018,
              "name": "Sennheiser - Binaural Headphone - Black",
              "customerReviewAverage": "4.5",
              "shortDescription": "Stereo - Black - Wireless - RF - 60 ft - 32 Ohm - 18 Hz 21 kHz - Over-the-head - Binaural - Circumaural",
              "image": "http://images.bestbuy.com/BestBuy_US/images/products/9637/9637018_sa.jpg",
              "salePrice": 199.99
            },
            {
              "sku": 9636974,
              "name": "Sennheiser - Binaural Headphone - Black",
              "customerReviewAverage": "4.4",
              "shortDescription": "Wired Connectivity - Surround - Over-the-head - Black",
              "image": "http://img.bbystatic.com/BestBuy_US/images/products/9636/9636974_rc.jpg",
              "salePrice": 69.99
            },
            {
              "sku": 9678429,
              "name": "Sennheiser - Camera-Mount Wireless Microphone System - Black",
              "customerReviewAverage": null,
              "shortDescription": "SENNHEISER Camera-Mount Wireless Microphone System: Invisible clip-on microphone; sturdy metal housing; automatic frequency management; easy-to-read illuminated display; 4-level battery indicator; 626-668MHz frequency range",
              "image": "http://images.bestbuy.com/BestBuy_US/images/products/9678/9678429_sa.jpg",
              "salePrice": 629.95
            },
            {
              "sku": 9678447,
              "name": "Sennheiser - Camera-Mount Wireless Microphone System - Black",
              "customerReviewAverage": null,
              "shortDescription": "SENNHEISER Camera-Mount Wireless Microphone System: Invisible clip-on microphone; sturdy metal housing; automatic frequency management; easy-to-read illuminated display; 4-level battery indicator; 566-608MHz frequency range",
              "image": "http://images.bestbuy.com/BestBuy_US/images/products/9678/9678447_sa.jpg",
              "salePrice": 629.95
            },
            {
              "sku": 6131454,
              "name": "Sennheiser - CH 650 S 10' Balanced Headphone Cable - Black",
              "customerReviewAverage": null,
              "shortDescription": "SENNHEISER CH 650 S 10' Balanced Headphone Cable: Compatible with Sennheiser headphone amplifiers; oxygen-free copper cables; gold-plated contacts; 4pole XLR with 2 mini plugs",
              "image": "http://images.bestbuy.com/BestBuy_US/images/products/6131/6131454_sa.jpg",
              "salePrice": 239.99
            },
            {
              "sku": 6131463,
              "name": "Sennheiser - CH 700 S 10' Balanced Headphone Cable - Black",
              "customerReviewAverage": null,
              "shortDescription": "SENNHEISER CH 700 S 10' Balanced Headphone Cable: Compatible with Sennheiser headphones and headphone amplifiers; oxygen-free copper cables with silver coating; gold-plated contacts; 4pole XLR with two 2.5mm jacks",
              "image": "http://img.bbystatic.com/BestBuy_US/images/products/6131/6131463_rc.jpg",
              "salePrice": 319.99
            },
            {
              "sku": 6131445,
              "name": "Sennheiser - CH 800 S 10' Balanced Headphone Cable - Black",
              "customerReviewAverage": null,
              "shortDescription": "SENNHEISER CH 800 S 10' Balanced Headphone Cable: Compatible with Sennheiser headphones and headphone amplifiers; oxygen-free copper cables with silver coating; gold-plated contacts; 4pole XLR with 2 ODU connectors",
              "image": "http://img.bbystatic.com/BestBuy_US/images/products/6131/6131445_rc.jpg",
              "salePrice": 379.99
            }
          ]
        }
    http_version: 
  recorded_at: Tue, 08 Mar 2016 19:00:25 GMT
recorded_with: VCR 3.0.1
